FormidableLabs/prism-react-renderer

package.json
So we can go to the GitHub repo from NPM
=> Add git repository field

.babelrc, .npmignore, package.json, yarn.lock
=> chore: Remove babel config from package.json

src/components/Highlight.js
Fix #16 
This doesn't use `getDerivedStateFromProps` to provide backwards compatibility without a polyfill. it also involves state in general since it's likely that the lib needs to rerender when the user prompts it too.
@pomber: Would you like to verify whether this solves the issue for you? :)
=> Fix Highlight component not updating themeDict

tools/themeFromVsCode/package.json, tools/themeFromVsCode/src/index.js
Trying to port my theme, but it has comments in it. Using JSON5 to parse the theme contents will allow this tool to read themes with comments in them
=> Use JSON5 for theme reading

tools/themeFromVsCode/README.md
Thanks for this project! Added some instructions for how to generate the `theme.json` file.
=> Add instructions for how to generate theme file

themes/palenight.js
Please note that I used the "Palenight Operator" variation of this VSCode theme to generate this.
=> Add Palenight theme

.gitignore, .npmignore, package.json, prism/package.json, rollup.config.js, src/defaultProps.js, src/themes/dracula.js, src/themes/duotoneDark.js, src/themes/duotoneLight.js, src/themes/github.js, src/themes/nightOwl.js, src/themes/nightOwlLight.js, src/themes/oceanicNext.js, src/themes/palenight.js, src/themes/shadesOfPurple.js, src/themes/ultramin.js, src/themes/vsDark.js, src/vendor/prism/prism-core.js, tools/themeFromVsCode/src/template.js, yarn.lock
=> Implement bundled ES/CJS Rollup build

README.md
Pretty cool component thanks a lot 🙌🙏
=> docs: Fix link to duotoneDark.js

src/themes/palenight.js
=> Add diff syntax highlighting support for Palenight theme

README.md
Updated deps, added editor example
Thanks for a great React lib!
=> update CodeSandbox example

README.md
- fixes typo in README
- use details/summary correctly 
- add link to supported languages
=> fix: typo in README and add link

README.md
It took me a while to figure out how to pass a new bundled theme to the `<Highlight />` component; so thought I'd add an example to README for others looking to do the same 😄 
🙌  Thanks for your work - really enjoy using the component!
=> Added bundled theming example to README

src/themes/vsDark.js
Hi @kitten ! 👋 Hope you are well!
Here's a small PR to slightly improve the VS Code Dark (`vsDark`) theme.
Before:
After:
Real VS Code:
=> Improve theme styles

package.json
=> invoke patch-package as a prebuild script

src/vendor/prism/index.js
- this tweaks the Prism vendor script to additionally account for `optional` dependencies
- prompted by https://github.com/FormidableLabs/prism-react-renderer/pull/150, but this should be a more holistic fix
- other langs may have been broken too 😅
- e.g. in the case of `markdown`, we were correctly prioritizing `markup` but not `yaml`
- see https://github.com/PrismJS/prism/blob/master/components.json#L873-L879
- n.b. only optional dependencies listed in the [`includedLangs`](https://github.com/FormidableLabs/prism-react-renderer/blob/master/src/vendor/prism/includeLangs.js) actually get included though
- (additional `console.log` temporarily added for illustration)
- note the order the `includedLangs` are added in
=> account for optional dependencies in Prism vendor script

src/vendor/prism/includeLangs.js
=> add markup-templating to includedLangs

.changeset/config.json, .github/workflows/release.yml, .github/workflows/static-analysis.yml, .github/workflows/unit-test.yml, package.json, packages/prism-react-renderer/src/utils/normalizeTokens.ts, pnpm-lock.yaml
Connects GitHub actions and changesets for prism-react-renderer
=> Add GitHub Actions + Changesets

.changeset/swift-squids-cheat.md, .github/workflows/release.yml, packages/prism-react-renderer/package.json
Sets up publishing provenance.
=> Provenance config

README.md
Sorry, forgot a parens in the previous PR :/
=> Fixup: Update README.md with correct link

README.md
=> ✏️ fix typo

.changeset/sweet-kiwis-shop.md, packages/demo/src/sample-code.ts, packages/generate-prism-languages/index.ts
Add JSON as a default supported language in Prism React Renderer.
Fixes # (issue)
To test on local :
1. clone the repo and checkout to this branch `208-add-json-to-the-default-included-languages`
2. pnpm install 
3. pnpm build
4. pnpm start:demo
localhost has a new option "JSON"
=> 208 add json to the default included languages
