FormidableLabs/prism-react-renderer

src/components/Highlight.js, src/components/__tests__/Highlight.test.js, src/components/__tests__/__snapshots__/Highlight.test.js.snap
Fix #3
When no grammar for a language in Prism is present,
the editor should just render with plain string tokens.
This changes the behaviour to let `normalizeTokens` run
through `[code]` when this edge case occurs.
=> Handle unsupported languages gracefully

package.json, themes/shadesOfPurple.js, tools/themeFromVsCode/README.md, tools/themeFromVsCode/package.json
With this PR I intend to add my VSCode theme 🦄 [Shades of Purple](https://marketplace.visualstudio.com/items?itemName=ahmadawais.shades-of-purple) to prism-react-render.
I converted the theme and manually edited it to make sure it looks good. Here's [demo of how it looks](https://codesandbox.io/s/2x39ky20my):
Since there is no contribution guide I had to figure things out on the go and found out that Husky need prettier which was not installed/required as a devDependency in the project. Assumption of having it installed globally is a bit much IMO. So, I added it in there.
I also wrote basic documentation for someone looking to generate a theme like I did. Thanks for working out the prism theme generator.
Added an npm script to easily run the theme generator.
Looking forward, peace! ✌️
=> Add 🦄 Shades of Purple Theme + Scripts + Docs

themes/vsDark.js, themes/vsDarkPlus.js
@kitten I'm sorry I just love these themes 😎😝
=> Add vs-code Dark Themes

src/components/__tests__/__snapshots__/Highlight.test.js.snap, src/utils/__tests__/normalizeTokens.test.js, src/utils/normalizeTokens.js
Fix #9 
Previously the assumption was made that nested "plain"
string tokens inside other typed tokens should still
*only* be of type "plain". Instead they should cascade
their styles.
So when the nested types array is: ["tag", "punctuation"],
and we encounter a plain string, the output type should be
the same types array.
=> Fix normalizeTokens overriding "plain" cascading types

src/components/__tests__/Highlight.test.js, src/utils/themeToDict.js
Fix #11 
The problem was the token that had the type "constructor", so the themeDict returned the `constructor` from the Object prototype.
But don't merge this yet, Flow complains that `Object.create(null)` is not a valid `ThemeDict`. I don't know how to fix that (never used Flow).
=> Remove constructor function from themeDict prototype

index.d.ts, package.json
=> TypeScript integration

themes/github.js
This PR add the github theme to list of themes present. The colors were originally taken from [here](https://raw.githubusercontent.com/zeit/docs/dc85902cecbe0e24f8ff52bb8f6e12045e107ed6/pages/docs/api/v1/api-docs-mdx/errors/domains.mdx). Although i had to make some modifications to fonts to make it look better.
Fixes issue https://github.com/FormidableLabs/prism-react-renderer/issues/32
Demo
=> Add github theme to the List of available themes

src/vendor/prism/includeLangs.js
Adds `tsx` to include langs. 
Currently using `tsx` with `react-live` and can't get syntax highlighting.
=> feat: add tsx support

package.json
Your [npm page](https://www.npmjs.com/package/prism-react-renderer) doesn't have a link to this repo; so this will add one!
=> Update package.json so NPM shows link to GitHub repo

src/components/__tests__/__snapshots__/Highlight.test.js.snap, src/utils/__tests__/normalizeTokens.test.js, src/utils/normalizeTokens.js
Adresses #78 
Currently when copy + pasting, empty lines are not preserved in the output, which could be unexpected for the user.
Adding a newline `\n` as the content for empty rows seems to help preserve newlines when copy + pasting; without adding any additional characters (e.g. whitespace) or changing the visuals.
I've tested this on macOS & windows, but haven't been able to test on a linux device
[x] macOS
[x] Windows
[ ] Unix
- Updated to expect `\n` as content for empty lines
- Updated as empty line spans are no-longer self-closing
I shimmed this functionality into the codesandbox example, so it can be tested:
https://codesandbox.io/s/prism-react-renderer-example-r8dl3
> note - the line numbers example seems to paste with extra newlines even in the original example, so I don't think …
=> Preserve newlines on copy + paste

src/components/Highlight.js, src/themes/dracula.js, src/themes/duotoneDark.js, src/themes/duotoneLight.js, src/themes/github.js, src/themes/nightOwl.js, src/themes/nightOwlLight.js, src/themes/oceanicNext.js, src/themes/palenight.js, src/themes/shadesOfPurple.js, src/themes/synthwave84.js, src/themes/ultramin.js, src/themes/vsDark.js, src/utils/normalizeTokens.js, src/utils/themeToDict.js
This will prevent unwanted changes when committing files. Some files are missing the prettier format and have different endline characters
=> run yarn format

package.json, src/defaultProps.js, src/index.js, src/types.js, src/utils/__tests__/normalizeTokens.test.js, src/utils/__tests__/themeToDict.test.js, src/vendor/prism/includeLangs.js, src/vendor/prism/index.js, src/vendor/prism/prism-core.js
Follow up on https://github.com/FormidableLabs/prism-react-renderer/pull/106
I noticed that not all `js` files under `src` were linted. The `format` script was using `src/**/*.js` glob, but per https://github.com/prettier/prettier/issues/2078#issuecomment-307539076 it should be enclosed in single quotes to function properly. Otherwise, it would only look for `js` files in a first-level directory such as `src/components/Highlight.js` and not `src/vendor/prism/prism-core.js` nor `src/types.js`
=> Fix prettier glob to correctly navigate recursively and format missing files

src/components/Highlight.js, src/types.js, src/vendor/prism/prism-core.js
Closes https://github.com/FormidableLabs/prism-react-renderer/issues/104
Based on https://github.com/PrismJS/prism/blob/022f90a0bf8ac7e40373d1b783354715b0a1020f/prism.js#L606-L616
With this change, users with custom languages can also provide a custom version of Prism to make languages such as `ERB` to work with `<Highlight>`
=> Call prism `before-tokenize` and `after-tokenize` hooks

src/themes/okaidia.js
Ported over from:
https://github.com/PrismJS/prism/blob/1761513e3db48ca9222037644a9c68746e24f039/themes/prism-okaidia.css
Happy to get @ocodia's blessing here.
=> Add Okaidia theme

src/themes/vsLight.js
Converted automatically using ./tools/themeFromVsCode
=> Add VS Light theme

README.md
=> Docs: Update README for React 18 ReactDOM.createRoot API

README.md, package.json, packages/prism-react-renderer/package.json, patches/prismjs@1.29.0.patch, pnpm-lock.yaml
- Moves our vendor-provided version of Prism to `1.29.0` and removes `patch-package` for pnpm's own patching.
- Updates the README for the new API changes
Please kick the tires and run the demo/build to make sure this all works on clean machines.
=> Bump to Prism 1.29, update README

.changeset/afraid-geese-fry.md, README.md, packages/demo/package.json, packages/demo/src/App.tsx, packages/demo/src/sample-code.ts, packages/generate-prism-languages/index.ts, packages/prism-react-renderer/src/components/highlight.ts, pnpm-lock.yaml
- Updates docs to demonstrate custom lanugages
- Adds Madi's two PR changes to the v2 codebase (#180 and #176)
- Adds AppleScript as a demo example of custom languages
=> Release v2 with updated API

.changeset/cold-cows-joke.md, packages/generate-prism-languages/index.ts, packages/prism-react-renderer/package.json, packages/prism-react-renderer/src/types.ts, pnpm-lock.yaml
Ensure `@types/prismjs` is a dependency for prism-react-renderer.
Addresses #195
=> Fix dependent types for PrismJS

.changeset/unlucky-crews-act.md, packages/prism-react-renderer/.gitignore, packages/prism-react-renderer/package.json
On prepublish, copy root README into package directory so it gets published to NPM.
=> Package readme

.changeset/popular-seals-occur.md, packages/prism-react-renderer/src/types.ts
Previously we had custom definitions—this is no longer needed with using the latest published version of Prism.
Addresses #203 
👇🏻 Now with using the library types, there are no ts errors
=> Fix types for `prism` library prop.

README.md
See discussion at https://github.com/FormidableLabs/prism-react-renderer/issues/190 which was probably closed by mistake?
=> Fix broken links to supported languages in README.md

.changeset/fair-spies-itch.md, packages/prism-react-renderer/src/index.ts
Export all types from `./types`. Prism React Renderer has a lot of utility types that can be useful to the consumer and they were previously exported in 1.x.
Addresses #211
=> Export all types from package

.changeset/many-eyes-travel.md, packages/demo/src/sample-code.ts, packages/generate-prism-languages/index.ts
Add Python support to languages.
Addresses #210
=> Add Python support.

.changeset/dry-icons-repeat.md, packages/demo/src/sample-code.ts, packages/generate-prism-languages/index.ts
- Swaps out the `html` preset  for `markdown` which does not code highlight the javascript inside a `<script />` tag
- Addresses https://github.com/facebook/docusaurus/issues/9517#issuecomment-1806142190
- Updated demo app to handle this case
Example of JavaScript inside a script tag now being highlighted inside a HTML file:
=> Fix HTML preset not highlighting script tags

.changeset/clsx-2.0.0.md, packages/prism-react-renderer/package.json, pnpm-lock.yaml
Changes from clsx from their release note:
> Add "exports" map for native ESM support
=> Upgrade clsx to 2.0.0

.changeset/tasty-cats-check.md, README.md, packages/prism-react-renderer/src/index.ts
Exports the two utility methods and adds documentation on them to the README
Addresses #236
=> Export `normalizeTokens` and `useTokenize` utility functions.

README.md
Starting React 18.3, this kind of code:
```jsx
const lineTokens = line.map((token, key) => (
<span key={key} {...getTokenProps({token, key})} />
));
```
leads to the following warning:
```
Warning: A props object containing a "key" prop is being spread into JSX:
let props = {key: someKey, className: ..., children: ..., style: ...};
<span {...props} />
React keys must be passed directly to JSX without using spread:
let props = {className: ..., children: ..., style: ...};
<span key={someKey} {...props} />
at CodeBlockLine (webpack-internal:///../packages/docusaurus-theme-classic/lib/theme/CodeBlock/Line/index.js:10:26)
```
I think the doc is a bit confusing (it led us to historically write the code above, although it's not what you show in the examples) while the key should rather be kept …
=> React 19 docs - do not advise to add a key in `getLineProps` + `getTokenProps`
